### ISSUE TITLE
HTTPS support?

### ISSUE THREAD

**Issue by khionu** [sidoh/reactor_simulator#10]
If you could at least add an HTTPS proxy (Let'sEncrypt is your friend), that would be great.

**Comment by sidoh** [comment]
I use LE pretty heavily for other stuff.  It wouldn't be hard.

i must ask...

![image](https://user-images.githubusercontent.com/589893/43101765-fb58c04a-8e7d-11e8-91a3-19f7be548fd8.png)

not that it hurts :)

**Comment by khionu** [comment]
Why not? As you said, it's easy enough, and it's that much more privacy on the web.

**Comment by sidoh** [comment]
Still not convinced it matters as much as you're suggesting in this case, or at all for that matter.

But anyway, done.  Lucky for you I already had certbot installed on the relevant machine. :)

Now no one can steal your sweet-ass reactor designs.

**Comment by khionu** [comment]
Much appreciated.
