### ISSUE TITLE
does this actually work?

### ISSUE THREAD

**Issue by chrisbecke** [sidoh/reactor_simulator#8]
Throwing together test reactors in the website, and a simple diamond filled and cyrotheum filled reactor supposedly both run at crazy hot temps. I'm not playing a BR modpack at the moment so I can't build reactors to test the simulator but I am suspicious of the online version.

**Comment by sidoh** [comment]
This is a weird way to open an issue. It's fine if you suspect a problem, but you probably shouldn't open an issue unless you have evidence that something is incorrect.

I think there is some weird behavior with very small reactors and with heat values for actively cooled reactors, but in my experience (and in the many people that use this daily), power output and fuel consumption is close to correct for most reactors. There have also been others that have tested values.

Feel free to re-open if you test in-game.
